### PR TITLE
stop duplicate ajax call for same query term

### PR DESCRIPTION
**Pull request by ravinderk**
stop duplicate ajax call for same query term by taking leverage of browser caching( i'm storing search results for per session ).

### CODE REVIEW

**Comment by ravinderk** [comment]
check this image https://docs.google.com/file/d/0B77zJcigGSUIRm9LdHlQcngweTA/edit

**Comment by ravinderk** [comment]
I did not see any activity on this pull request, so I am close it.

**Comment by tomjn** [comment]
Keep in mind that CFTP as an entity no longer exists, perhaps @scottsweb would know how to test this, but I'm mindful that there are a lot of unrelated changes in this that may be undesirable, especially around code formatting

**Comment by scottsweb** [comment]
Thanks for the ping, I agree that closing this is the best path. Shortcode discovery seems like a distant concern when looking through the lens of Gutenberg.

**Pull request closed without merging**
